//DnumSpecificWindows.h
#ifndef NUMSW
#define NUMSW 
	#define NUMSPECIFICWINDOWS 24
	#define NUMPREFPANELS (NUMSPECIFICWINDOWS + 1)
	//array indexes make enums??
	#define SPECIFIC_COLOR_BUTTON 0
	#define SPECIFIC_COLOR_PICTURE 1
	#define SPECIFIC_COLOR_RADIOVIEW 2
	#define SPECIFIC_COLOR_CHECKBOX 3
	#define SPECIFIC_COLOR_STATUSBAR 4
	#define SPECIFIC_COLOR_COLORCONTROL 5
	#define SPECIFIC_COLOR_COLORWELL 6
	#define SPECIFIC_COLOR_INT8GADGET 7
	#define SPECIFIC_COLOR_UINT8GADGET 8
	#define SPECIFIC_COLOR_INT16GADGET 9
	#define SPECIFIC_COLOR_UINT16GADGET 10
	#define SPECIFIC_COLOR_INT32GADGET 11
	#define SPECIFIC_COLOR_UINT32GADGET 12
	#define SPECIFIC_COLOR_INT64GADGET 13
	#define SPECIFIC_COLOR_UINT64GADGET 14
	#define SPECIFIC_COLOR_FLOATGADGET 15
	#define SPECIFIC_COLOR_STRINGGADGET 16
	#define SPECIFIC_COLOR_STRINGCONTROL 17
	#define SPECIFIC_COLOR_TEXTVIEW 18
	#define SPECIFIC_COLOR_STRINGDRAWER 19
	#define SPECIFIC_COLOR_LISTVIEW 20
	#define SPECIFIC_COLOR_FLOATCONTROL 21
	#define SPECIFIC_COLOR_UINT32CONTROL 22
	#define SPECIFIC_COLOR_SLIDER 23
#endif